config/routes.rb
Rails.application.routes.draw do
  
=begin  match '*' => 'home#coming_soon', as: :coming_soon
=end

	mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root  'home#index'

post '/' => 'home#index'
get '/about-me' => 'about#show', as: :about_show
get '/blog' => 'blog#index', as: :blog_index
get '/consultation-success' => 'consultation_thanku#index', as: :cunsulation_index
get '/lean-program-success' => 'lean_program_thanku#index', as: :lean_index
get '/reverse-success' => 'reversetype_thanku#index', as: :reverse_index

get '/blog/:slug' => 'blog#show', as: :blog_show
get '/contact-us' => 'contact#show', as: :contact_show
# get '/gallery' => 'gallery#show', as: :gallery_show
get '/consultation' => 'consultation#index', as: :consultation_show
get '/coming-soon' => 'home#coming_soon', as: :coming_soon
get '/program/:slug' => 'programs#show', as: :program_show

get 'checkout' => 'checkout#index', as: :checkout_index
get 'program-checkout' => 'program_checkout#index', as: :program_checkout_index
get 'client-assesment' => 'client_assesment#index', as: :client_assesment_index

post '/bookings' => 'bookings#create', as: :create_bookings
post '/temp_bookings' => 'temp_bookings#create', ad: :temp_bookings

   	get '/mail-design' => 'mail_designs#new'
   	post '/mail-design' => 'mail_designs#create'
   	post '/enquiry' => 'enquiry#create'

   	get '/marketing-emails' => 'emailer#show'
	post '/marketing-emails' => 'emailer#create', as: :marketing_emails_create
    get '/emailer/template' => 'emailer#template'
	 post '/contact-us' => 'contact#submit'
get '/client-assessment' => 'feedback#show', as: :feedback_show

end

app/models/about_me.rb
class AboutMe < ApplicationRecord
		mount_uploader :img, AvatarUploader
		mount_uploader :bg, AvatarUploader

	rails_admin do

		 edit do
		 	include_all_fields
	      	field :certificate_points, :ck_editor do
	      		config_js ActionController::Base.helpers.asset_path('ckeditor/config.js')
	      	end
		end
    end

end

app/models/blog.rb
class Blog < ApplicationRecord
extend FriendlyId
  	friendly_id :heading, use: :slugged
	mount_uploader :img, AvatarUploader

rails_admin do

	    	edit do

		      field :heading
		      field :desc
		      field :img
		      field :video_link
		     field :symmery_one, :ck_editor do
	      		config_js ActionController::Base.helpers.asset_path('ckeditor/config.js')
	    	end
	    end
		    
		end
end

app/models/booking.rb
class Booking < ApplicationRecord
	before_create :create_uid
	after_create :send_mails

	def create_uid
	    self.uid = loop do
	      	random_uid = "SHRO#{rand.to_s[2..11]}"
	      	break random_uid unless Booking.exists?(uid: random_uid)
	   	end
	end

	def self.get_boking_type(amount)
		if amount.to_i <= 1000
			return 'slot_booking'
		else
			return 'program_booking'

		end
	end

	def send_mails
		if self.status == 'captured'
			# if self.amount == 200
				BookingMailer.admin_mail(self).deliver_now
				BookingMailer.customer_mail(self).deliver_now
			# else
			# 	ProgramMailer.admin_mail(self).deliver_now
			# 	ProgramMailer.customer_mail(self).deliver_now
			# end	
			
		end
	end
	rails_admin do
			show do
		      field :uid
		      field :status
		      field :amount
		      field :currency
		      field :email
		      field :phone
		     
		  
	    	end
	    	edit do
		      field :uid
		      field :status
		      field :amount
		      field :currency
		      field :email
		      field :phone
		     
	    	end
		    list do
		      field :uid
		      field :email
		      field :phone
		      field :status
		      field :amount
		      field :currency
		     
		    end
		end

end

app/models/consultation.rb
class Consultation < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/faq_datum.rb
class FaqDatum < ApplicationRecord
end

app/models/input_header.rb
class InputHeader < ApplicationRecord
end

app/models/input_text.rb
class InputText < ApplicationRecord
end

app/models/mail_design.rb
class MailDesign < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader
end

app/models/mail_template.rb
class MailTemplate < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord
	extend FriendlyId
  	friendly_id :heading, use: :slugged
	mount_uploader :img, AvatarUploader
	# has_rich_text :content_two
		rails_admin do

	 edit do
		 	field :heading
		 	field :short_desc
		 	field :paragraph_one
		 	field :paragraph_two
		 	field :amount
		 	field :amount
		 	field :payment_link
		 	field :actual_price
		 	field :discount
	 		field :slug
	  		field :img
	    	field :video_link
	      	field :content, :ck_editor do
	      		config_js ActionController::Base.helpers.asset_path('ckeditor/config.js')
end
	    end
end     

end

app/models/short_intro.rb
class ShortIntro < ApplicationRecord
	mount_uploader :img, AvatarUploader
end

app/models/six_point.rb
class SixPoint < ApplicationRecord
	mount_uploader :icon, AvatarUploader
end

app/models/slider.rb
class Slider < ApplicationRecord
		mount_uploader :img, AvatarUploader
end

app/models/slot_booking.rb
class SlotBooking < Booking
	enum timings: {"1:00 PM" => '1:00 PM', "2:00 PM" => "2:00 PM", "3:00 PM" => "3:00 PM", "4:00 PM" => "4:00 PM", "5:00 PM" => "5:00 PM", "6:00 PM" => "6:00 PM"}

	rails_admin do
		show do
	      field :uid
	      field :status
	      field :amount
	      field :currency
	      field :email
	      field :phone
	      field :type
	      field :booking_date
	      field :booking_time
	  
    	end
    	edit do
	      field :uid
	      field :status
	      field :amount
	      field :currency
	      field :email
	      field :phone
	      field :type
	      field :booking_date
	      field :booking_time
    	end
	    list do
	      field :uid
	      field :email
	      field :phone
	      field :booking_date
	      field :booking_time
	      field :status
	      field :amount
	      field :currency
	      field :type
	     
	    end
	end
end

app/models/temp_booking.rb
class TempBooking < ApplicationRecord
	validates_inclusion_of :booking_type, :in => ['slot_booking', 'program_booking']
	validates_inclusion_of :booking_time, :in => ["1:00 PM","1:30 PM","2:00 PM","2:30 PM","3:00 PM","3:30 PM","4:00 PM","4:30 PM","5:00 PM","5:30 PM","6:00 PM"], if: :slot_booking
	before_save :validate_date, if: :slot_booking
	validates_presence_of :email
	validates_presence_of :phone
	validates_presence_of :booking_date
	validates_presence_of :booking_time
	validates_presence_of :booking_type
	validates_presence_of :amount

		
	def validate_date
		if (self.booking_date.to_date < Date.today) || (self.booking_date.to_date == Date.today && self.booking_time.to_time < Time.now)
			self.errors.add(:booking_date, "Invalid Date")
			throw(:abort)
		else
			self.booking_date = self.booking_date.to_date
		end
	end
	def slot_booking
	    self.booking_type == 'slot booking'
	end
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
		@sliders = Slider.all
		@points = SixPoint.all
		@intros = ShortIntro.all
		@testimonials = TestimonialClient.all
		@inputheader = InputHeader.first
		@inputtext = InputText.first
	end
	def submit
		contact = Contact.new(contact_params)
		if contact.save
		flash[:success] = 'Thanks, Your contact request is generated. We will contact you soon!'
		# ContactMailer.send_contact_mail(params).deliver_now
		# ContactMailer.customer_mail(params).deliver_now
		else
			flash[:notice] = 'Oops! Something went wrong.'
		end
		redirect_to root_path
	end

	private
	def contact_params
		params.permit(:name, :email, "", "")
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/coming_soon.html.erb
<!DOCTYPE html>
<html class="cspio">
<head>
	
	<!-- Font Awesome CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">

	<!-- Bootstrap and default Style -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" >
	<link rel="stylesheet" href="https://static.comingsoonpage.com/cspio-assets/1.0.0/style.css">

	<!-- Google Fonts -->
	<link class="gf-headline" href='https://fonts.googleapis.com/css?family=Pacifico:400&subset=' rel='stylesheet' type='text/css'>
			
	<!-- Animate CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.1/animate.min.css">
	
	<!-- Calculated Styles -->
	<style type="text/css">
	
	html {
		height: 100%;
		overflow: hidden;
	}

	body {
		height:100%;
		overflow: auto;
		-webkit-overflow-scrolling: touch;
	}
	
	html{
		height:100%;
		background: #ffffff url(https://image.freepik.com/free-photo/room-with-concrete-floor-smoke-with-light-from-spotlights-background_9083-2993.jpg); no-repeat center bottom fixed;
		-webkit-background-size: cover;
		-moz-background-size: cover;
		-o-background-size: cover;
		background-size: cover;
	}

	#cspio-page{
		background-color: rgba(0,0,0,0);
	}
	
	.flexbox #cspio-page{
		align-items: center;
		justify-content: center;
	}

	.cspio body{
		background: transparent;
	}

	.cspio body, .cspio body p{
        font-family: Helvetica, Arial, sans-serif;
		font-weight: 400;
		font-style: ;
        font-size: 20px;
        line-height: 1.50em;
        color:#ffffff;
    }

	::-webkit-input-placeholder {
		font-family:Helvetica, Arial, sans-serif;
		font-weight: 400;
		font-style: ;
	}

	::-moz-placeholder {
		font-family:Helvetica, Arial, sans-serif;
		font-weight: 400;
		font-style: ;
	} 

	:-ms-input-placeholder {
		font-family:Helvetica, Arial, sans-serif;
		font-weight: 400;
		font-style: ;
	} 

	:-moz-placeholder {
		font-family:Helvetica, Arial, sans-serif;
		font-weight: 400;
		font-style: ;
	}

    .cspio h1, .cspio h2, .cspio h3, .cspio h4, .cspio h5, .cspio h6{
        font-family: 'Pacifico';
        color:#ffffff;
    }

	#cspio-headline{
		font-family: 'Pacifico';
		font-weight: 400;
		font-style: ;
				font-size: 48px;
		color:#ffffff;
		line-height: 1.00em;
	}

	.cspio button{
        font-family: Helvetica, Arial, sans-serif;
		font-weight: 400;
		font-style: ;
    }
	
    .cspio a, .cspio a:visited, .cspio a:hover, .cspio a:active{
		color: #ffffff;
	}

	#cspio-socialprofiles a {
	  color: #ffffff;
	}
	.cspio .btn-primary,
	.cspio .btn-primary:focus,
	.gform_button,
	#mc-embedded-subscribe, .submit-button {
		color: black;
		text-shadow: 0 -1px 0 rgba(255,255,255,0.3);
		background-color: #ffffff;
		background-image: -moz-linear-gradient(top,#ffffff,#d9d9d9);
		background-image: -ms-linear-gradient(top,#ffffff,#d9d9d9);
		background-image: -webkit-gradient(linear,0 0,0 100%,from(#ffffff),to(#d9d9d9));
		background-image: -webkit-linear-gradient(top,#ffffff,#d9d9d9);
		background-image: -o-linear-gradient(top,#ffffff,#d9d9d9);
		background-image: linear-gradient(top,#ffffff,#d9d9d9);
		background-repeat: repeat-x;
		filter: progid:DXImageTransform.Microsoft.gradient(startColorstr='#ffffff', endColorstr='#d9d9d9', GradientType=0);
		border-color: #d9d9d9 #d9d9d9 #b3b3b3;
		border-color: rgba(0,0,0,0.1) rgba(0,0,0,0.1) rgba(0,0,0,0.25);
		*background-color: #d9d9d9;
		filter: progid:DXImageTransform.Microsoft.gradient(enabled = false);
	}

	.cspio .btn-primary:hover,
	.cspio .btn-primary:active,
	.cspio .btn-primary.active,
	.cspio .btn-primary.disabled,
	.cspio .btn-primary[disabled],
	.cspio .btn-primary:focus:hover,
	.cspio .btn-primary:focus:active,
	.cspio .btn-primary:focus.active,
	.cspio .btn-primary:focus.disabled,
	.cspio .btn-primary:focus[disabled],
	#mc-embedded-subscribe:hover,
	#mc-embedded-subscribe:active,
	#mc-embedded-subscribe.active,
	#mc-embedded-subscribe.disabled,
	#mc-embedded-subscribe[disabled] {
		background-color: #d9d9d9;
		*background-color: #cccccc;
	}

	.cspio .btn-primary:active,
	.cspio .btn-primary.active,
	.cspio .btn-primary:focus:active,
	.cspio .btn-primary:focus.active,
	.gform_button:active,
	.gform_button.active,
	#mc-embedded-subscribe:active,
	#mc-embedded-subscribe.active {
		background-color: #bfbfbf;
	}

	.form-control,
	.progress {
		background-color: rgba(255, 255, 255, 0.85);
	}

	#cspio-progressbar span,
	.countdown_section {
		color: black;
		text-shadow: 0 -1px 0 rgba(255,255,255,0.3);
	}

	.cspio .btn-primary:hover,
	.cspio .btn-primary:active {
		color: black;
		text-shadow: 0 -1px 0 rgba(255,255,255,0.3);
		border-color: #e6e6e6;
	}

	.cspio input[type='text']:focus {
		webkit-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075), 0 0 8px rgba(217,217,217,0.6);
		-moz-box-shadow: inset 0 1px 1px rgba(0,0,0,0.075), 0 0 8px rgba(217,217,217,0.6);
		box-shadow: inset 0 1px 1px rgba(0,0,0,0.075), 0 0 8px rgba(217,217,217,0.6);
	}
    
    #cspio-content {
		display: none;
		max-width: 600px;
		background-color: #000000;
		-webkit-border-radius: 2px;
		border-radius: 2px;
		-moz-background-clip: padding;
		-webkit-background-clip: padding-box;
		background-clip: padding-box;
		background-color:transparent;
	}
    
	.cspio .progress-bar,
	.countdown_section,
	.cspio .btn-primary,
	.cspio .btn-primary:focus,
	.gform_button {
		background-image: none;
		text-shadow: none;
	}

	.cspio input,
	.cspio input:focus {
		-webkit-box-shadow: none !important;
		box-shadow: none !important;
	}
							
	#cspio-page{
	    background: -moz-radial-gradient(ellipse at center, rgba(0, 0, 0, 0.3) 0%,rgba(0, 0, 0, 0.2) 37%,rgba(0,0,0,0) 68%,rgba(0,0,0,0) 100%);
	    background: -webkit-radial-gradient(ellipse at center, rgba(0, 0, 0, 0.3) 0%,rgba(0, 0, 0, 0.2) 37%,rgba(0,0,0,0) 68%,rgba(0,0,0,0) 100%);
	    background: radial-gradient(ellipse at center, rgba(0, 0, 0, 0.3) 0%,rgba(0, 0, 0, 0.2) 37%,rgba(0,0,0,0) 68%,rgba(0,0,0,0) 100%);
	}

	.cspio body{
		background: -moz-radial-gradient(center, ellipse cover,  rgba(0,0,0,0) 7%, rgba(0,0,0,0) 80%, rgba(0,0,0,0.23) 100%); 
		background: -webkit-radial-gradient(center, ellipse cover,  rgba(0,0,0,0) 7%,rgba(0,0,0,0) 80%,rgba(0,0,0,0.23) 100%); 
		background: radial-gradient(ellipse at center,  rgba(0,0,0,0) 7%,rgba(0,0,0,0) 80%,rgba(0,0,0,0.23) 100%); 
		filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#00000000', endColorstr='#3b000000',GradientType=1 ); 
	}

	#cspio-subscribe-btn{
	    background:transparent;
	    border: 1px solid #fff !important;
	    color: #fff;
	}

	#cspio-subscribe-btn:hover{
	    background: rgba(255,255,255,0.2);
	    color: #fff;
	}

	#cspio-credit img{
		margin-left:auto;
		margin-right:auto;
		width:125px;
		    margin-top: -4px;
	}

	#cspio-credit {
		font-size:11px;
	}

	</style>

	<!-- jQuery -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

	<!-- Modernizr -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
	
	<!-- Google Analytics Code Goes Here-->
</head>
<body>
	<div id="cspio-page">
		<div id="cspio-content">
			
			<img id="cspio-logo" src="assets/logo.png">
			    				
			<h1 id="cspio-headline">Workshops Coming Soon</h1>			    				
			
			<div id="cspio-description">Get ready! Something really cool is coming!</div>			    				
			
		
					    						    			    								    			    			    				
			<div id="cspio-socialprofiles">
				<a href="https://www.instagram.com/theshehrozalam" target="_blank"><i class="fa fa-instagram"></i></a>
				<a href="https://twitter.com/theshehrozalam" target="_blank"><i class="fa fa-twitter"></i></a>
				<a href="https://www.facebook.com/theshehrozalam" target="_blank"><i class="fa fa-facebook"></i></a>	
			</div>


									    									    			    			    							    			     			    		
		</div><!-- end of #cspio-content -->
	</div>


	<script>
		// Animate Delay
		setTimeout(function(){ jQuery("#cspio-content").show().addClass('animated fadeIn'); }, 250);

		// Reseize	
		function resize(){
				$('head').append("<style id='form-style' type='text/css'></style>");
				$('#form-style').html('.cspio .input-group-btn, .cspio .input-group{display:block;width:100%;}.cspio #cspio-subscribe-btn{margin-left:0;width:100%;display:block;}.cspio .input-group .form-control:first-child, .cspio .input-group-addon:first-child, .cspio .input-group-btn:first-child>.btn, .cspio .input-group-btn:first-child>.dropdown-toggle, .cspio .input-group-btn:last-child>.btn:not(:last-child):not(.dropdown-toggle) {border-bottom-right-radius: 4px;border-top-right-radius: 4px;}.cspio .input-group .form-control:last-child, .cspio .input-group-addon:last-child, .cspio .input-group-btn:last-child>.btn, .cspio .input-group-btn:last-child>.dropdown-toggle, .cspio .input-group-btn:first-child>.btn:not(:first-child) {border-bottom-left-radius: 4px;border-top-left-radius: 4px;}');
		}
		
		$('#cspio-content').one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', 
			function(){
				var width = $('#cspio-field-wrapper').width();
				if(width < 480 && width != 0){
					resize();
				}
			}
		);
	</script>

	</body>
</html>

app/views/home/index.html.erb
<%= render partial: 'shared/header' %>

<section class="hero-section">
<div>
	  <img src="https://wallpaperplay.com/walls/full/4/7/b/40696.jpg" alt="" style="width: 100%; height: 150px;"  />

</div>

<div id="my-carousel" class="owl-carousel owl-theme">
	 <% @sliders.each do |slider| %>

		<div class="item">
			  <div class="custom_overlay_wrapper">
				  	<a><img src="<%= slider.img_url %>">
				  		<div class="custom_overlay">
					  		<span class="custom_overlay_inner">
					  			<% if slider.link == nil %>	
					  			<p><b><%= slider.heading %></b>
					  			</p>
								<% else %>
								<h4 href="<%= slider.link %>" class="primary-btn video-popup">Play Now</b>
									<i class="fa fa-play"></i>
					  			</h4>
								
								<% end %>	
							</span>
						</div>
					</a>
				</div>
		 </div>

 	<% end %>

  </div>
  
</section>

<section class="classes-section">
<div class="class-title set-bg" data-setbg="assets/classes-title-bg.jpg">
<div class="container">
<div class="row">
<div class="col-lg-7 m-auto text-center">
<div class="section-title pl-lg-4 pr-lg-4 pl-0 pr-0">
<h2><%= @inputheader.heading %></h2>
<p><%= @inputheader.desc %></p>
</div>
</div>
</div>
</div>
</div>
<div class="container-fluid">
</div>
</section>
<section class="feature-section" id="programs" >
<div class="container-fluid">
<div  class="row">
<% @programs.each_with_index do |program,index| %>
 <% if index < 3 %>

<div class="col-md-4">
<div class="feature-item set-bg" data-setbg="<%= program.img_url %>">
<h3><%= program.heading %></h3>
<p><%= program.short_desc %></p>
<a href="<%= program_show_path(slug: program.slug) %>" data-turbolinks="false" class="primary-btn f-btn">Buy Now</a>
</div>
</div>
<% end %>
<% end %>

</div>
</div>
</section>
<section class="cta-section">
<div class="container">
<div class="row">
	<div class="col-lg-7 m-auto text-center">

	<div class="section-title pl-lg-4 pr-lg-4 pl-0 pr-0">

		<div class="leave-comment-form" style="margin-top: 20px;">
		<h4><%= @inputtext.heading %></h4>
		<p><%= @inputtext.desc %></p>

		<%= form_tag '/enquiry', id: "contact-form" do %> 
		<div class="row" style="margin-top: 20px;">
		<div class="col-lg-4">
		<input type="text" placeholder="<%= @inputtext.name_value %>" name="name" id="name" required>
		</div>
		<div class="col-lg-4">
		<input type="email" placeholder="<%= @inputtext.email_value %>" name="email" id="email" required>
		</div>

		<div class="col-lg-4">
		<button type="submit" class="leave-btn" style="
		    background: white;
		    color: orangered; padding-top: 13px; padding-bottom: 13px;">SUBMIT</button>
		</div>
		 </div>
		<% end %>
		</div>
</div>
</div>
</div>
</div>
</section>

<section class="home-about spad">
<div class="container">
<% @intros.each do |intro| %>

<div class="row">
<div class="col-lg-6">
<div class="about-text">
<h2><%= intro.heading %></h2>
<p class="short-details"><%= intro.description %></p>
<p class="long-details"><%= intro.short_desc %></p>
<a href="/about-me" data-turbolinks="false" class="primary-btn about-btn">Read More</a>
</div>
</div>
<div class="col-lg-6">
<div class="about-img">
<img src="<%= intro.img.url %>" alt="about_me">
</div>
</div>
</div>
<% end %>
</div>
</section>




<section class="chooseus-section spad">
<div class="container">
<div class="row">
<div class="col-lg-12">
<div class="section-title">
<h2>Why choose Shehroz Alam Fitness and Nutrition</h2>
</div>
</div>
</div>
<div class="row">
<% @points.each do |point| %>
<div class="col-lg-4 col-sm-6">
<div class="choose-item">
<img src="<%= point.icon_url %>" alt="icon" style="
    width: 50px;">
<h5><%= point.heading %></h5>
<p><%= point.description %></p>
</div>
</div>
<% end %>


</div>
</div>
</section>

<section class="trainer-section spad">
	<% if @testimonials.size > 0 %>	

<div class="container">
<div class="row">
<div class="col-lg-12">
<div class="section-title">
<h2>Testimonials</h2>
<p>Join our family and start your journey.</p>
</div>
</div>
</div>
<div class="scroll">
<div class="row">

<% @testimonials.each do |testimonial| %>

<div class="col-lg-3 col-sm-6">
<div class="trainer-item">
<div class="ti-pic">
<iframe src="<%= testimonial.video_link %>"
   width="100%" height="400px" frameborder="0" allowfullscreen></iframe>
</div>
</div>
</div>

<% end %>
</div>
</div>
</div>
<% end %>

</section>


<%= render partial: 'shared/footer' %>