config/routes.rb
Rails.application.routes.draw do
  
=begin  match '*' => 'home#coming_soon', as: :coming_soon
=end

	mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

root  'home#index'

post '/' => 'home#index'
get '/about-me' => 'about#show', as: :about_show
get '/blog' => 'blog#index', as: :blog_index
get '/consultation-success' => 'consultation_thanku#index', as: :cunsulation_index
get '/lean-program-success' => 'lean_program_thanku#index', as: :lean_index
get '/reverse-success' => 'reversetype_thanku#index', as: :reverse_index

get '/blog/:slug' => 'blog#show', as: :blog_show
get '/contact-us' => 'contact#show', as: :contact_show
# get '/gallery' => 'gallery#show', as: :gallery_show
get '/consultation' => 'consultation#index', as: :consultation_show
get '/coming-soon' => 'home#coming_soon', as: :coming_soon
get '/program/:slug' => 'programs#show', as: :program_show

get 'checkout' => 'checkout#index', as: :checkout_index
get 'program-checkout' => 'program_checkout#index', as: :program_checkout_index
get 'client-assesment' => 'client_assesment#index', as: :client_assesment_index

post '/bookings' => 'bookings#create', as: :create_bookings
post '/temp_bookings' => 'temp_bookings#create', ad: :temp_bookings

   	get '/mail-design' => 'mail_designs#new'
   	post '/mail-design' => 'mail_designs#create'
   	post '/enquiry' => 'enquiry#create'

   	get '/marketing-emails' => 'emailer#show'
	post '/marketing-emails' => 'emailer#create', as: :marketing_emails_create
    get '/emailer/template' => 'emailer#template'
	 post '/contact-us' => 'contact#submit'
get '/client-assessment' => 'feedback#show', as: :feedback_show

end

app/models/about_me.rb
class AboutMe < ApplicationRecord
		mount_uploader :img, AvatarUploader
		mount_uploader :bg, AvatarUploader

	rails_admin do

		 edit do
		 	include_all_fields
	      	field :certificate_points, :ck_editor do
	      		config_js ActionController::Base.helpers.asset_path('ckeditor/config.js')
	      	end
		end
    end

end

app/models/blog.rb
class Blog < ApplicationRecord
extend FriendlyId
  	friendly_id :heading, use: :slugged
	mount_uploader :img, AvatarUploader

rails_admin do

	    	edit do

		      field :heading
		      field :desc
		      field :img
		      field :video_link
		     field :symmery_one, :ck_editor do
	      		config_js ActionController::Base.helpers.asset_path('ckeditor/config.js')
	    	end
	    end
		    
		end
end

app/models/booking.rb
class Booking < ApplicationRecord
	before_create :create_uid
	after_create :send_mails

	def create_uid
	    self.uid = loop do
	      	random_uid = "SHRO#{rand.to_s[2..11]}"
	      	break random_uid unless Booking.exists?(uid: random_uid)
	   	end
	end

	def self.get_boking_type(amount)
		if amount.to_i <= 1000
			return 'slot_booking'
		else
			return 'program_booking'

		end
	end

	def send_mails
		if self.status == 'captured'
			# if self.amount == 200
				BookingMailer.admin_mail(self).deliver_now
				BookingMailer.customer_mail(self).deliver_now
			# else
			# 	ProgramMailer.admin_mail(self).deliver_now
			# 	ProgramMailer.customer_mail(self).deliver_now
			# end	
			
		end
	end
	rails_admin do
			show do
		      field :uid
		      field :status
		      field :amount
		      field :currency
		      field :email
		      field :phone
		     
		  
	    	end
	    	edit do
		      field :uid
		      field :status
		      field :amount
		      field :currency
		      field :email
		      field :phone
		     
	    	end
		    list do
		      field :uid
		      field :email
		      field :phone
		      field :status
		      field :amount
		      field :currency
		     
		    end
		end

end

app/models/consultation.rb
class Consultation < ApplicationRecord
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/models/faq_datum.rb
class FaqDatum < ApplicationRecord
end

app/models/input_header.rb
class InputHeader < ApplicationRecord
end

app/models/input_text.rb
class InputText < ApplicationRecord
end

app/models/mail_design.rb
class MailDesign < ApplicationRecord
	mount_uploader :attachment, AttachmentUploader
end

app/models/mail_template.rb
class MailTemplate < ApplicationRecord
end

app/models/program.rb
class Program < ApplicationRecord
	extend FriendlyId
  	friendly_id :heading, use: :slugged
	mount_uploader :img, AvatarUploader
	# has_rich_text :content_two
		rails_admin do

	 edit do
		 	field :heading
		 	field :short_desc
		 	field :paragraph_one
		 	field :paragraph_two
		 	field :amount
		 	field :amount
		 	field :payment_link
		 	field :actual_price
		 	field :discount
	 		field :slug
	  		field :img
	    	field :video_link
	      	field :content, :ck_editor do
	      		config_js ActionController::Base.helpers.asset_path('ckeditor/config.js')
end
	    end
end     

end

app/models/short_intro.rb
class ShortIntro < ApplicationRecord
	mount_uploader :img, AvatarUploader
end

app/models/six_point.rb
class SixPoint < ApplicationRecord
	mount_uploader :icon, AvatarUploader
end

app/models/slider.rb
class Slider < ApplicationRecord
		mount_uploader :img, AvatarUploader
end

app/models/slot_booking.rb
class SlotBooking < Booking
	enum timings: {"1:00 PM" => '1:00 PM', "2:00 PM" => "2:00 PM", "3:00 PM" => "3:00 PM", "4:00 PM" => "4:00 PM", "5:00 PM" => "5:00 PM", "6:00 PM" => "6:00 PM"}

	rails_admin do
		show do
	      field :uid
	      field :status
	      field :amount
	      field :currency
	      field :email
	      field :phone
	      field :type
	      field :booking_date
	      field :booking_time
	  
    	end
    	edit do
	      field :uid
	      field :status
	      field :amount
	      field :currency
	      field :email
	      field :phone
	      field :type
	      field :booking_date
	      field :booking_time
    	end
	    list do
	      field :uid
	      field :email
	      field :phone
	      field :booking_date
	      field :booking_time
	      field :status
	      field :amount
	      field :currency
	      field :type
	     
	    end
	end
end

app/models/temp_booking.rb
class TempBooking < ApplicationRecord
	validates_inclusion_of :booking_type, :in => ['slot_booking', 'program_booking']
	validates_inclusion_of :booking_time, :in => ["1:00 PM","1:30 PM","2:00 PM","2:30 PM","3:00 PM","3:30 PM","4:00 PM","4:30 PM","5:00 PM","5:30 PM","6:00 PM"], if: :slot_booking
	before_save :validate_date, if: :slot_booking
	validates_presence_of :email
	validates_presence_of :phone
	validates_presence_of :booking_date
	validates_presence_of :booking_time
	validates_presence_of :booking_type
	validates_presence_of :amount

		
	def validate_date
		if (self.booking_date.to_date < Date.today) || (self.booking_date.to_date == Date.today && self.booking_time.to_time < Time.now)
			self.errors.add(:booking_date, "Invalid Date")
			throw(:abort)
		else
			self.booking_date = self.booking_date.to_date
		end
	end
	def slot_booking
	    self.booking_type == 'slot booking'
	end
end

app/models/testimonial.rb
class Testimonial < ApplicationRecord
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def show
		@faqs = FaqDatum.all
	end
	def submit
		contact = Contact.new(contact_params)
		if contact.save
		flash[:success] = 'Thanks, Your contact request is generated. We will contact you soon!'
		# ContactMailer.send_contact_mail(params).deliver_now
		# ContactMailer.customer_mail(params).deliver_now
		else
			flash[:notice] = 'Oops! Something went wrong.'
		end
		redirect_to root_path
	end

	private
	def contact_params
		params.permit(:name, :email, :subject, :message)
	end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contact/show.html.erb
<%= render partial: 'shared/header' %>


<section class="contact-section spad">
<div class="container"style="margin-top: 70px;">
<div class="row">
<div class="col-lg-3">
<div class="contact-info">
<h4>Information</h4>
<ul>
<li><i class="fa fa-phone"></i>(+91) 9910772367</li>
<li><i class="fa fa-envelope"></i><a href="mailto:info@shehrozalam.com" class="__cf_email__">info@shehrozalam.com</a></li>
</ul>
</div>
<div class="contact-address">
<h4>Address</h4>
<ul>
<li><i class="fa fa-map-marker"></i> New Friends Colony, Delhi-IND
</li>
</ul>
</div>
</div>
<div class="col-lg-8 offset-lg-1">
<div class="contact-form">
<h4>Get in touch</h4>
<%= form_tag contact_us_path, id: "contact-form" do %> 
<div class="row">
<div class="col-lg-6">
<input type="text" placeholder="Name" name="name" id="name" required>
</div>
<div class="col-lg-6">
<input type="email" placeholder="Email" name="email" id="email" required>
</div>
<div class="col-lg-12">
<textarea placeholder="Message" name="message" id="message" required></textarea>
<button type="submit" class="c-btn">Send Message</button>
</div>
</div>
<% end %>
</div>
</div>
</div>
</div>
</section>
<% if @faqs.size > 0 %>	

<section class="classes-section">
<div class="container">
<div class="row">
<div class="col-lg-7 m-auto text-center">
<div class="section-title pl-lg-4 pr-lg-4 pl-0 pr-0">
<h2>FAQS</h2>
<p> QUESTIONS AND ANSWERS</p>
</div>
</div>
</div>
</div>
</div>

<div class="container" style="margin-top: 50px;">
    <div class="row">
       
        <div class="col-lg-12">
            <div class="tab-content" id="faq-tab-content">
                <div class="tab-pane show active" id="tab1" role="tabpanel" aria-labelledby="tab1">
                    <div class="accordion" id="accordion-tab-1">
                       <% @faqs.each_with_index do |faq,index| %>

                        <div class="card">
                            <div class="card-header" id="accordion-tab-1-heading-2">
                                <h5>
                                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#accordion-tab-1-content-<%= index %>" aria-expanded="false" aria-controls="accordion-tab-1-content-2"><%= faq.heading %></button>
                                </h5>
                            </div>
                            <div class="collapse" id="accordion-tab-1-content-<%= index %>" aria-labelledby="accordion-tab-1-heading-2" data-parent="#accordion-tab-1">
                                <div class="card-body">
                                    <p><%= faq.desc %></p>
                                </div>
                            </div>
                        </div>
                        <% end %>
                       
                    </div>
                </div>
                
            </div>
        </div>
    </div>
</div>
</section>
<% end %>
<%= render partial: 'shared/footer' %>